#!/bin/bash
# Setup Terraform Remote Backend (S3 + DynamoDB)

set -e

export AWS_PROFILE=magic-account
export AWS_REGION=us-east-1

echo "🔧 Setting up Terraform Remote Backend..."
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(dirname "$SCRIPT_DIR")/terraform"

cd "$TERRAFORM_DIR"

# Get AWS Account ID
echo "📋 Getting AWS Account ID..."
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --profile magic-account)

if [ -z "$ACCOUNT_ID" ]; then
  echo "❌ Could not get AWS Account ID. Check your AWS credentials."
  exit 1
fi

echo "✓ Account ID: $ACCOUNT_ID"
echo ""

# Step 1: Initialize Terraform (local state)
echo "🔧 Step 1: Initializing Terraform with local state..."
terraform init

# Step 2: Deploy backend infrastructure
echo ""
echo "🏗️  Step 2: Creating S3 bucket and DynamoDB table for remote state..."
terraform apply -target=aws_s3_bucket.terraform_state \
                -target=aws_s3_bucket_versioning.terraform_state \
                -target=aws_s3_bucket_server_side_encryption_configuration.terraform_state \
                -target=aws_s3_bucket_public_access_block.terraform_state \
                -target=aws_dynamodb_table.terraform_locks \
                -auto-approve

BUCKET_NAME="magic-cert-terraform-state-${ACCOUNT_ID}"
echo ""
echo "✓ Backend infrastructure created:"
echo "  - S3 Bucket: $BUCKET_NAME"
echo "  - DynamoDB Table: magic-cert-terraform-locks"
echo ""

# Step 3: Create backend.tf from template
echo "📝 Step 3: Creating backend.tf configuration..."
cat > backend.tf << EOF
# Terraform Remote Backend Configuration
# Auto-generated by setup-backend.sh

terraform {
  backend "s3" {
    bucket         = "${BUCKET_NAME}"
    key            = "production/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "magic-cert-terraform-locks"
    encrypt        = true
    profile        = "magic-account"
  }
}
EOF

echo "✓ Created backend.tf"
echo ""

# Step 4: Migrate state to S3
echo "🔄 Step 4: Migrating state to S3..."
echo ""
terraform init -migrate-state

echo ""
echo "✅ Remote backend setup complete!"
echo ""
echo "📦 Your Terraform state is now stored in:"
echo "   s3://${BUCKET_NAME}/production/terraform.tfstate"
echo ""
echo "🔒 State locking enabled with DynamoDB table:"
echo "   magic-cert-terraform-locks"
echo ""
echo "🚀 You can now run: terraform apply"
